name: Build and publish to GHCR

on:
  release:
    types: [ published ]
  push:
    branches:
      - master

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and publish
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          platforms: "linux/amd64,linux/arm/v7,linux/arm64"
